// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/domains.proto

package proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ListDomainsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListDomainsRequest) Reset()         { *m = ListDomainsRequest{} }
func (m *ListDomainsRequest) String() string { return proto.CompactTextString(m) }
func (*ListDomainsRequest) ProtoMessage()    {}
func (*ListDomainsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_domains_4b7d101a01714825, []int{0}
}
func (m *ListDomainsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListDomainsRequest.Unmarshal(m, b)
}
func (m *ListDomainsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListDomainsRequest.Marshal(b, m, deterministic)
}
func (dst *ListDomainsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListDomainsRequest.Merge(dst, src)
}
func (m *ListDomainsRequest) XXX_Size() int {
	return xxx_messageInfo_ListDomainsRequest.Size(m)
}
func (m *ListDomainsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListDomainsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListDomainsRequest proto.InternalMessageInfo

type ListDomainsResponse struct {
	Domains              []*Domain `protobuf:"bytes,1,rep,name=domains,proto3" json:"domains,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ListDomainsResponse) Reset()         { *m = ListDomainsResponse{} }
func (m *ListDomainsResponse) String() string { return proto.CompactTextString(m) }
func (*ListDomainsResponse) ProtoMessage()    {}
func (*ListDomainsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_domains_4b7d101a01714825, []int{1}
}
func (m *ListDomainsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListDomainsResponse.Unmarshal(m, b)
}
func (m *ListDomainsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListDomainsResponse.Marshal(b, m, deterministic)
}
func (dst *ListDomainsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListDomainsResponse.Merge(dst, src)
}
func (m *ListDomainsResponse) XXX_Size() int {
	return xxx_messageInfo_ListDomainsResponse.Size(m)
}
func (m *ListDomainsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListDomainsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListDomainsResponse proto.InternalMessageInfo

func (m *ListDomainsResponse) GetDomains() []*Domain {
	if m != nil {
		return m.Domains
	}
	return nil
}

type Domain struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	NameServers          []string `protobuf:"bytes,3,rep,name=name_servers,json=nameServers,proto3" json:"name_servers,omitempty"`
	Status               string   `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Domain) Reset()         { *m = Domain{} }
func (m *Domain) String() string { return proto.CompactTextString(m) }
func (*Domain) ProtoMessage()    {}
func (*Domain) Descriptor() ([]byte, []int) {
	return fileDescriptor_domains_4b7d101a01714825, []int{2}
}
func (m *Domain) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Domain.Unmarshal(m, b)
}
func (m *Domain) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Domain.Marshal(b, m, deterministic)
}
func (dst *Domain) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Domain.Merge(dst, src)
}
func (m *Domain) XXX_Size() int {
	return xxx_messageInfo_Domain.Size(m)
}
func (m *Domain) XXX_DiscardUnknown() {
	xxx_messageInfo_Domain.DiscardUnknown(m)
}

var xxx_messageInfo_Domain proto.InternalMessageInfo

func (m *Domain) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Domain) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Domain) GetNameServers() []string {
	if m != nil {
		return m.NameServers
	}
	return nil
}

func (m *Domain) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type GetDomainRecordsRequest struct {
	DomainName           string   `protobuf:"bytes,1,opt,name=domain_name,json=domainName,proto3" json:"domain_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetDomainRecordsRequest) Reset()         { *m = GetDomainRecordsRequest{} }
func (m *GetDomainRecordsRequest) String() string { return proto.CompactTextString(m) }
func (*GetDomainRecordsRequest) ProtoMessage()    {}
func (*GetDomainRecordsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_domains_4b7d101a01714825, []int{3}
}
func (m *GetDomainRecordsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDomainRecordsRequest.Unmarshal(m, b)
}
func (m *GetDomainRecordsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDomainRecordsRequest.Marshal(b, m, deterministic)
}
func (dst *GetDomainRecordsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDomainRecordsRequest.Merge(dst, src)
}
func (m *GetDomainRecordsRequest) XXX_Size() int {
	return xxx_messageInfo_GetDomainRecordsRequest.Size(m)
}
func (m *GetDomainRecordsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDomainRecordsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetDomainRecordsRequest proto.InternalMessageInfo

func (m *GetDomainRecordsRequest) GetDomainName() string {
	if m != nil {
		return m.DomainName
	}
	return ""
}

type GetDomainRecordsResponse struct {
	Records              []*DomainRecord `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *GetDomainRecordsResponse) Reset()         { *m = GetDomainRecordsResponse{} }
func (m *GetDomainRecordsResponse) String() string { return proto.CompactTextString(m) }
func (*GetDomainRecordsResponse) ProtoMessage()    {}
func (*GetDomainRecordsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_domains_4b7d101a01714825, []int{4}
}
func (m *GetDomainRecordsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDomainRecordsResponse.Unmarshal(m, b)
}
func (m *GetDomainRecordsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDomainRecordsResponse.Marshal(b, m, deterministic)
}
func (dst *GetDomainRecordsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDomainRecordsResponse.Merge(dst, src)
}
func (m *GetDomainRecordsResponse) XXX_Size() int {
	return xxx_messageInfo_GetDomainRecordsResponse.Size(m)
}
func (m *GetDomainRecordsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDomainRecordsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetDomainRecordsResponse proto.InternalMessageInfo

func (m *GetDomainRecordsResponse) GetRecords() []*DomainRecord {
	if m != nil {
		return m.Records
	}
	return nil
}

type DomainRecord struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type                 string   `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Content              string   `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	Ttl                  int32    `protobuf:"varint,5,opt,name=ttl,proto3" json:"ttl,omitempty"`
	ZoneName             string   `protobuf:"bytes,6,opt,name=zone_name,json=zoneName,proto3" json:"zone_name,omitempty"`
	Data                 string   `protobuf:"bytes,7,opt,name=data,proto3" json:"data,omitempty"`
	Priority             int32    `protobuf:"varint,8,opt,name=priority,proto3" json:"priority,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DomainRecord) Reset()         { *m = DomainRecord{} }
func (m *DomainRecord) String() string { return proto.CompactTextString(m) }
func (*DomainRecord) ProtoMessage()    {}
func (*DomainRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_domains_4b7d101a01714825, []int{5}
}
func (m *DomainRecord) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DomainRecord.Unmarshal(m, b)
}
func (m *DomainRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DomainRecord.Marshal(b, m, deterministic)
}
func (dst *DomainRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DomainRecord.Merge(dst, src)
}
func (m *DomainRecord) XXX_Size() int {
	return xxx_messageInfo_DomainRecord.Size(m)
}
func (m *DomainRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_DomainRecord.DiscardUnknown(m)
}

var xxx_messageInfo_DomainRecord proto.InternalMessageInfo

func (m *DomainRecord) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *DomainRecord) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *DomainRecord) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *DomainRecord) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *DomainRecord) GetTtl() int32 {
	if m != nil {
		return m.Ttl
	}
	return 0
}

func (m *DomainRecord) GetZoneName() string {
	if m != nil {
		return m.ZoneName
	}
	return ""
}

func (m *DomainRecord) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func (m *DomainRecord) GetPriority() int32 {
	if m != nil {
		return m.Priority
	}
	return 0
}

func init() {
	proto.RegisterType((*ListDomainsRequest)(nil), "io.jerryho.srv.cloudflare.ListDomainsRequest")
	proto.RegisterType((*ListDomainsResponse)(nil), "io.jerryho.srv.cloudflare.ListDomainsResponse")
	proto.RegisterType((*Domain)(nil), "io.jerryho.srv.cloudflare.Domain")
	proto.RegisterType((*GetDomainRecordsRequest)(nil), "io.jerryho.srv.cloudflare.GetDomainRecordsRequest")
	proto.RegisterType((*GetDomainRecordsResponse)(nil), "io.jerryho.srv.cloudflare.GetDomainRecordsResponse")
	proto.RegisterType((*DomainRecord)(nil), "io.jerryho.srv.cloudflare.DomainRecord")
}

func init() { proto.RegisterFile("proto/domains.proto", fileDescriptor_domains_4b7d101a01714825) }

var fileDescriptor_domains_4b7d101a01714825 = []byte{
	// 393 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x53, 0x4d, 0x4f, 0xc2, 0x40,
	0x10, 0x4d, 0x29, 0xb4, 0x30, 0x10, 0x63, 0x16, 0xa3, 0x2b, 0x1e, 0x2c, 0xbd, 0xd8, 0x8b, 0x35,
	0x81, 0x9b, 0x9e, 0x34, 0x26, 0x5c, 0x8c, 0x87, 0xf5, 0x66, 0x62, 0x48, 0xa5, 0xab, 0xd6, 0x40,
	0xb7, 0xee, 0x6e, 0x49, 0xf0, 0xcf, 0xf9, 0x73, 0xfc, 0x1b, 0x66, 0x3f, 0x4a, 0x30, 0x08, 0xea,
	0x69, 0x67, 0x5e, 0xe7, 0xcd, 0xce, 0x7b, 0x3b, 0x85, 0x6e, 0xc1, 0x99, 0x64, 0x67, 0x29, 0x9b,
	0x25, 0x59, 0x2e, 0x62, 0x9d, 0xa1, 0xc3, 0x8c, 0xc5, 0xaf, 0x94, 0xf3, 0xc5, 0x0b, 0x8b, 0x05,
	0x9f, 0xc7, 0x93, 0x29, 0x2b, 0xd3, 0xa7, 0x69, 0xc2, 0x69, 0xb8, 0x07, 0xe8, 0x26, 0x13, 0xf2,
	0xda, 0xd4, 0x13, 0xfa, 0x56, 0x52, 0x21, 0x43, 0x02, 0xdd, 0x6f, 0xa8, 0x28, 0x58, 0x2e, 0x28,
	0xba, 0x00, 0xdf, 0x36, 0xc6, 0x4e, 0xe0, 0x46, 0xed, 0x41, 0x3f, 0xde, 0xd8, 0x39, 0x36, 0x64,
	0x52, 0x31, 0xc2, 0x67, 0xf0, 0x0c, 0x84, 0x76, 0xa0, 0x96, 0xa5, 0xd8, 0x09, 0x9c, 0xa8, 0x45,
	0x6a, 0x59, 0x8a, 0x10, 0xd4, 0xf3, 0x64, 0x46, 0x71, 0x4d, 0x23, 0x3a, 0x46, 0x7d, 0xe8, 0xa8,
	0x73, 0x2c, 0x28, 0x9f, 0x53, 0x2e, 0xb0, 0x1b, 0xb8, 0x51, 0x8b, 0xb4, 0x15, 0x76, 0x67, 0x20,
	0xb4, 0x0f, 0x9e, 0x90, 0x89, 0x2c, 0x05, 0xae, 0x6b, 0xa2, 0xcd, 0xc2, 0x73, 0x38, 0x18, 0x51,
	0x3b, 0x3b, 0xa1, 0x13, 0xc6, 0xd3, 0x4a, 0x17, 0x3a, 0x86, 0xb6, 0x19, 0x67, 0xac, 0x2f, 0x34,
	0x23, 0x80, 0x81, 0x6e, 0x93, 0x19, 0x0d, 0x1f, 0x00, 0xaf, 0x73, 0xad, 0xfa, 0x4b, 0xf0, 0xb9,
	0x81, 0xac, 0xfa, 0x93, 0xdf, 0xd5, 0xeb, 0x7a, 0x52, 0xf1, 0xc2, 0x0f, 0x07, 0x3a, 0xab, 0x5f,
	0x7e, 0xb2, 0x42, 0x2e, 0x8a, 0xa5, 0x15, 0x2a, 0x5e, 0xda, 0xe3, 0xae, 0xd8, 0x83, 0xc1, 0x9f,
	0xb0, 0x5c, 0xd2, 0x5c, 0x5a, 0xf1, 0x55, 0x8a, 0x76, 0xc1, 0x95, 0x72, 0x8a, 0x1b, 0x81, 0x13,
	0x35, 0x88, 0x0a, 0xd1, 0x11, 0xb4, 0xde, 0x59, 0x4e, 0x8d, 0x64, 0x4f, 0x57, 0x37, 0x15, 0xa0,
	0x04, 0xab, 0xe6, 0x69, 0x22, 0x13, 0xec, 0x9b, 0xe6, 0x2a, 0x46, 0x3d, 0x68, 0x16, 0x3c, 0x63,
	0x3c, 0x93, 0x0b, 0xdc, 0xd4, 0x7d, 0x96, 0xf9, 0xe0, 0xd3, 0x01, 0xdf, 0xae, 0x05, 0xa2, 0x50,
	0x57, 0x5b, 0x82, 0x4e, 0xb7, 0xf8, 0xb0, 0xbe, 0x5c, 0xbd, 0xf8, 0xaf, 0xe5, 0xd6, 0xf7, 0x12,
	0x60, 0x44, 0xa5, 0x7d, 0x0d, 0x34, 0xd8, 0xc2, 0xde, 0xf0, 0xec, 0xbd, 0xe1, 0xbf, 0x38, 0xe6,
	0xda, 0x2b, 0xff, 0xbe, 0xa1, 0xff, 0x9e, 0x47, 0x4f, 0x1f, 0xc3, 0xaf, 0x00, 0x00, 0x00, 0xff,
	0xff, 0x4e, 0xfb, 0xd9, 0x24, 0x5b, 0x03, 0x00, 0x00,
}
